import os

from semantic_digital_twin.semantic_annotations.semantic_annotations import (
    Apple,
    Bottle,
    Bowl,
    Cereal,
    CoffeeTable,
    CounterTop,
    Dishwasher,
    Drawer,
    Fork,
    Kitchen,
    Knife,
    LivingRoom,
    Milk,
    Mug,
    Oven,
    Plate,
    SideTable,
    Sink,
    Spoon,
    Table,
)

from thesis_demo.world.environment import (
    ContainedPlacement,
    EnvironmentSpec,
    FurnitureAnnotation,
    RESOURCES,
    RoomSpec,
    SurfacePlacement,
)

APARTMENT = EnvironmentSpec(
    urdf=os.path.join(RESOURCES, "worlds", "apartment.urdf"),
    robot_start=(1.5, 2.5, 0.0),
    rooms=(
        RoomSpec(Kitchen, "kitchen", (3.0, 2.5), (6.0, 4.5)),
        RoomSpec(LivingRoom, "living_room", (17.0, 2.5), (3.5, 4.5)),
    ),
    furniture=(
        FurnitureAnnotation(CounterTop, "island_countertop"),
        FurnitureAnnotation(CounterTop, "countertop"),
        FurnitureAnnotation(Table, "table_area_main"),
        FurnitureAnnotation(CoffeeTable, "coffee_table"),
        FurnitureAnnotation(SideTable, "bedside_table"),
        FurnitureAnnotation(Sink, "sink"),
        FurnitureAnnotation(Oven, "oven"),
        FurnitureAnnotation(Dishwasher, "cabinet7"),
    ),
    surface_objects=(
        SurfacePlacement(
            Bowl,
            "bowl.stl",
            "island_countertop",
            (-0.20, -0.10),
            mesh="bowl.stl",
        ),
        SurfacePlacement(
            Cereal,
            "breakfast_cereal.stl",
            "island_countertop",
            (0.20, -0.10),
            mesh="breakfast_cereal.stl",
        ),
        SurfacePlacement(
            Milk,
            "milk.stl",
            "island_countertop",
            (-0.20, 0.10),
            mesh="milk.stl",
        ),
        SurfacePlacement(
            Bottle,
            "Static_CokeBottle.stl",
            "countertop",
            (0.0, 0.0),
            mesh="Static_CokeBottle.stl",
        ),
        SurfacePlacement(
            Mug,
            "mug_sink",
            "countertop",
            (-0.15, 0.10),
            scale=(0.08, 0.08, 0.10),
        ),
        SurfacePlacement(
            Mug,
            "jeroen_cup.stl",
            "table_area_main",
            (0.0, 0.0),
            mesh="jeroen_cup.stl",
        ),
        SurfacePlacement(
            Plate,
            "plate",
            "table_area_main",
            (-0.15, -0.10),
            scale=(0.18, 0.18, 0.02),
        ),
        SurfacePlacement(
            Plate,
            "plate_counter",
            "countertop",
            (0.15, -0.10),
            scale=(0.18, 0.18, 0.02),
        ),
        SurfacePlacement(
            Apple,
            "apple",
            "table_area_main",
            (-0.15, 0.10),
            scale=(0.08, 0.08, 0.08),
        ),
        SurfacePlacement(
            Apple,
            "apple_island",
            "island_countertop",
            (0.15, 0.10),
            scale=(0.08, 0.08, 0.08),
        ),
    ),
    contained_objects=(
        ContainedPlacement(
            Spoon,
            "spoon.stl",
            "cabinet10_drawer_top",
            Drawer,
            (-0.05, -0.10, 0.0),
            mesh="spoon.stl",
        ),
        ContainedPlacement(
            Fork,
            "fork",
            "cabinet10_drawer_top",
            Drawer,
            (-0.05, 0.0, 0.0),
            scale=(0.18, 0.02, 0.02),
        ),
        ContainedPlacement(
            Knife,
            "knife",
            "cabinet10_drawer_top",
            Drawer,
            (-0.05, 0.10, 0.0),
            scale=(0.18, 0.015, 0.02),
        ),
    ),
)
